workflow:
  rules:
    - if: '$CI_COMMIT_MESSAGE == "Applying package updates."'
      when: never
    - when: always

before_script:
  - echo "some before 1"
  - echo "some before 2"
  
stages: 
  - stage1
  - stage2


job1:
  stage: stage1
  only:
    - external_pull_requests
  script: 
    - echo "some job here1"

job2:
  stage: stage2
  script:
    - echo "some job execution 2"
